### PR TITLE
Aidan/draggable-widget merge request

### PR DESCRIPTION
**Pull request by lukecanny**
Theres a lotta stuff happening in this branch so just want to make this PR to make sure everything can merge correctly + we know exactly how far behind master branch is

### CODE REVIEW

**Comment by aidandempsey** [comment]
This PR several changes:

- Updated master's paper link
- Update project poster link
- Added functionality and validation for board IO (switches and LEDS)
- Added redirection to "help" MD files
-  Made UI widgets draggable and droppable
- Refactored a lot of IPyWidgets (and corresponding event handlers) into HTML, CSS and JS
- Added ability to scale up or down images (useful when multiple images of the different sizes)
- Added distinction of "Run Clock Period" for synchronous circuits, "Set Signals" for asynchronous circuits
- Updated the [docs/main_menu.png](https://github.com/Logicademy/PYNQ-SoC-Builder/pull/30/files#diff-e125f8d71bce1adc208bbd4de38084dc10b92d7560ce8664be9ff79b8fb7be41) image
- Added a PYNQ-SoC-Builder taskbar favicon

Hope I'm not leaving anything out! The board IO functionality and validation could be described in way more detail than I was able to here

**Comment by aidandempsey** [comment]
I tested this branch with the these [demo designs](https://github.com/aidandempsey/DemoDesigns) and tried to break it in as many ways as I could haha, I think I've covered everything but ye might be able to find more edge cases that cause errors. The ngrok boards are currently down but I will be able to do more testing locally on the PYNQ-Z1 when the USB adapter arrives

**Comment by aidandempsey** [comment]
Now have access to a remote board, will extensively test tomorrow and report results

**Comment by lukecanny** [comment]
Hi Aidan, absolutely outstanding. I have one more change to make.

- If Switches or Buttons are used as inputs, the automated testplan execution will always **fail** as inputs cannot be supplied by Jupyter Notebook (arm processor).

There is no fix, I just need to disable testplan generation and replace where it would be with a note to the user describing why.

Will be complete within next hour or two.

All going well, will be happy to merge tonight. Will test locally on Z2 before confirming.

**Review by aidandempsey — APPROVED** [review]
LGTM!

**Comment by lukecanny** [comment]
Disabled testplan generation if input IO is used 
Added markdown to explain this to user

**Comment by lukecanny** [comment]
Changing GUI to have the thread isn't a blocking feature. Merging our current changes. Will push that fix as soon as its there.

**Pull request merged**
