### PR TITLE
aidan/signal-threading

### PR DESCRIPTION
**Pull request by lukecanny**
Creating PR to see difference between main and this branch

### CODE REVIEW

**Comment by aidandempsey** [comment]
@lukecanny whenever you get the chance would you like to review this? I just tested it with the Mux2_1 but it seems to be working as expected

mux

**Comment by lukecanny** [comment]
Unreal Aidan! Yes I'll test it now :)

**Comment by aidandempsey** [comment]
Thank you man! There's a good few code cleanups in this too but they shouldn't change the functionality, the generated .py file easier to debug

**Comment by lukecanny** [comment]
Tested against the CB4CLED :) - Worked like a charm!

**Pull request merged**
